
USE WEIGHING_DB;
SET autocommit = 1;

-- REPLACE INTO `PERMISSIONS` SET permission_id = 'A', `permission` = 'Adat megtekintés';
-- REPLACE INTO `PERMISSIONS` SET permission_id = 'M', `permission` = 'Mérés készítés';
-- REPLACE INTO `PERMISSIONS` SET permission_id = 'T', `permission` = 'Törzsadat kezelés';
-- REPLACE INTO `PERMISSIONS` SET permission_id = 'F', `permission` = 'Felhasználó kezelés';
-- REPLACE INTO `PERMISSIONS` SET permission_id = 'B', `permission` = 'Beállítás kezelés';

REPLACE INTO `measurement_types` SET measurement_type_id = 'M', `measurement_type_name` = 'Mérlegelt adat';
REPLACE INTO `measurement_types` SET measurement_type_id = 'K', `measurement_type_name` = 'Kézzel megadott';
REPLACE INTO `measurement_types` SET measurement_type_id = 'G', `measurement_type_name` = 'Gépjármű tárolt súlya';

REPLACE INTO `movements` SET `movement_name` = 'Beszállítás', `movement_stock_relation`= '+', `movement_head` = 'MÉRLEGJEGY', `movement_left_side` = 'átvevő', `movement_right_side` = 'átadó', `movement_form_file_name` = 'merlegjegy.html';
REPLACE INTO `movements` SET `movement_name` = 'Kiszállítás', `movement_stock_relation`= '-', `movement_head` = 'SZÁLLÍTÓLEVÉL', `movement_left_side` = 'átadó', `movement_right_side` = 'átvevő', `movement_form_file_name` = 'szallito.html';
REPLACE INTO `movements` SET `movement_name` = 'Csak mérés', `movement_stock_relation`= ' ', `movement_head` = 'MÉRLEGELÉS', `movement_left_side` = '', `movement_right_side` = '', `movement_form_file_name` = 'merlegeles.html';
REPLACE INTO `movements` SET `movement_name` = 'Induló készlet', `movement_stock_relation`= '+', `movement_head` = 'INDULÓ KÉSZLET', `movement_left_side` = 'átvevő', `movement_right_side` = 'átadó', `movement_form_file_name` = 'merlegjegy.html';
REPLACE INTO `movements` SET `movement_name` = 'Selejtezés', `movement_stock_relation`= '-', `movement_head` = 'SELEJTEZÉS MÉRLEGJEGY', `movement_left_side` = 'átvevő', `movement_right_side` = 'átadó', `movement_form_file_name` = 'merlegjegy.html';
REPLACE INTO `movements` SET `movement_name` = 'Többlet készlet', `movement_stock_relation`= '+', `movement_head` = 'TÖBBLET LELTÁR KÉSZLET', `movement_left_side` = 'átvevő', `movement_right_side` = 'átadó', `movement_form_file_name` = 'merlegjegy.html';
REPLACE INTO `movements` SET `movement_name` = 'Leltár hiány', `movement_stock_relation`= '-', `movement_head` = 'LELTÁR HIÁNY MÉRLEGJEGY', `movement_left_side` = 'átvevő', `movement_right_side` = 'átadó', `movement_form_file_name` = 'merlegjegy.html';


REPLACE INTO `countries` SET country_code = 'HU', country_name = 'Magyarország';
REPLACE INTO `countries` SET country_code = 'AT', country_name = 'Ausztria';
REPLACE INTO `countries` SET country_code = 'BA', country_name = 'Bosznia-Hercegovina';
REPLACE INTO `countries` SET country_code = 'BE', country_name = 'Belgium';
REPLACE INTO `countries` SET country_code = 'BG', country_name = 'Bulgária';
REPLACE INTO `countries` SET country_code = 'CY', country_name = 'Ciprus';
REPLACE INTO `countries` SET country_code = 'CZ', country_name = 'Cseh Köztársaság';
REPLACE INTO `countries` SET country_code = 'DK', country_name = 'Dánia';
REPLACE INTO `countries` SET country_code = 'US', country_name = 'Egyesült Államok';
REPLACE INTO `countries` SET country_code = 'GB', country_name = 'Egyesült Királyság';
REPLACE INTO `countries` SET country_code = 'EE', country_name = 'Észtország';
REPLACE INTO `countries` SET country_code = 'FI', country_name = 'Finnország';
REPLACE INTO `countries` SET country_code = 'FR', country_name = 'Franciaország';
REPLACE INTO `countries` SET country_code = 'GR', country_name = 'Görögország';
REPLACE INTO `countries` SET country_code = 'NL', country_name = 'Hollandia';
REPLACE INTO `countries` SET country_code = 'HR', country_name = 'Horvátország';
REPLACE INTO `countries` SET country_code = 'IE', country_name = 'Írország';
REPLACE INTO `countries` SET country_code = 'PL', country_name = 'Lengyelország';
REPLACE INTO `countries` SET country_code = 'LV', country_name = 'Lettország';
REPLACE INTO `countries` SET country_code = 'LT', country_name = 'Litvánia';
REPLACE INTO `countries` SET country_code = 'LU', country_name = 'Luxemburg';
REPLACE INTO `countries` SET country_code = 'MT', country_name = 'Málta';
REPLACE INTO `countries` SET country_code = 'DE', country_name = 'Németország';
REPLACE INTO `countries` SET country_code = 'IT', country_name = 'Olaszország';
REPLACE INTO `countries` SET country_code = 'PT', country_name = 'Portugália';
REPLACE INTO `countries` SET country_code = 'RO', country_name = 'Románia';
REPLACE INTO `countries` SET country_code = 'ES', country_name = 'Spanyolország';
REPLACE INTO `countries` SET country_code = 'CH', country_name = 'Svájc';
REPLACE INTO `countries` SET country_code = 'SE', country_name = 'Svédor;szág';
REPLACE INTO `countries` SET country_code = 'XS', country_name = 'Szerbia';
REPLACE INTO `countries` SET country_code = 'SK', country_name = 'Szlovákia';
REPLACE INTO `countries` SET country_code = 'SI', country_name = 'Szlovénia';
REPLACE INTO `countries` SET country_code = 'UK', country_name = 'Ukrajna';


REPLACE INTO `street_types` SET `street_type` = 'út';
REPLACE INTO `street_types` SET `street_type` = 'utca';
REPLACE INTO `street_types` SET `street_type` = 'tér';
REPLACE INTO `street_types` SET `street_type` = 'köz';
REPLACE INTO `street_types` SET `street_type` = 'akna';
REPLACE INTO `street_types` SET `street_type` = 'akna-alsó';
REPLACE INTO `street_types` SET `street_type` = 'akna-felső';
REPLACE INTO `street_types` SET `street_type` = 'alagút';
REPLACE INTO `street_types` SET `street_type` = 'alsórakpart';
REPLACE INTO `street_types` SET `street_type` = 'arborétum';
REPLACE INTO `street_types` SET `street_type` = 'autóút';
REPLACE INTO `street_types` SET `street_type` = 'állat és növ.kert';
REPLACE INTO `street_types` SET `street_type` = 'állomás';
REPLACE INTO `street_types` SET `street_type` = 'árnyék';
REPLACE INTO `street_types` SET `street_type` = 'árok';
REPLACE INTO `street_types` SET `street_type` = 'átjáró';
REPLACE INTO `street_types` SET `street_type` = 'barakképület';
REPLACE INTO `street_types` SET `street_type` = 'barlang';
REPLACE INTO `street_types` SET `street_type` = 'bánya';
REPLACE INTO `street_types` SET `street_type` = 'bányatelep';
REPLACE INTO `street_types` SET `street_type` = 'bástya';
REPLACE INTO `street_types` SET `street_type` = 'bástyája';
REPLACE INTO `street_types` SET `street_type` = 'bejáró';
REPLACE INTO `street_types` SET `street_type` = 'bekötőút';
REPLACE INTO `street_types` SET `street_type` = 'csárda';
REPLACE INTO `street_types` SET `street_type` = 'csónakházak';
REPLACE INTO `street_types` SET `street_type` = 'domb';
REPLACE INTO `street_types` SET `street_type` = 'dűlő';
REPLACE INTO `street_types` SET `street_type` = 'dűlősor';
REPLACE INTO `street_types` SET `street_type` = 'dűlőterület';
REPLACE INTO `street_types` SET `street_type` = 'dűlőút';
REPLACE INTO `street_types` SET `street_type` = 'egyetemváros';
REPLACE INTO `street_types` SET `street_type` = 'egyéb';
REPLACE INTO `street_types` SET `street_type` = 'elágazás';
REPLACE INTO `street_types` SET `street_type` = 'emlékút';
REPLACE INTO `street_types` SET `street_type` = 'erdészház';
REPLACE INTO `street_types` SET `street_type` = 'erdészlak';
REPLACE INTO `street_types` SET `street_type` = 'erdő';
REPLACE INTO `street_types` SET `street_type` = 'erdősor';
REPLACE INTO `street_types` SET `street_type` = 'fasor';
REPLACE INTO `street_types` SET `street_type` = 'fasora';
REPLACE INTO `street_types` SET `street_type` = 'felső';
REPLACE INTO `street_types` SET `street_type` = 'forduló';
REPLACE INTO `street_types` SET `street_type` = 'föld';
REPLACE INTO `street_types` SET `street_type` = 'főmérnökség';
REPLACE INTO `street_types` SET `street_type` = 'főtér';
REPLACE INTO `street_types` SET `street_type` = 'főút';
REPLACE INTO `street_types` SET `street_type` = 'gát';
REPLACE INTO `street_types` SET `street_type` = 'gátőrház';
REPLACE INTO `street_types` SET `street_type` = 'gátsor';
REPLACE INTO `street_types` SET `street_type` = 'gyár';
REPLACE INTO `street_types` SET `street_type` = 'gyártelep';
REPLACE INTO `street_types` SET `street_type` = 'gyárváros';
REPLACE INTO `street_types` SET `street_type` = 'gyümölcsös';
REPLACE INTO `street_types` SET `street_type` = 'határsor';
REPLACE INTO `street_types` SET `street_type` = 'határút';
REPLACE INTO `street_types` SET `street_type` = 'ház';
REPLACE INTO `street_types` SET `street_type` = 'hegy';
REPLACE INTO `street_types` SET `street_type` = 'hegyhát';
REPLACE INTO `street_types` SET `street_type` = 'hegyhát dűlő';
REPLACE INTO `street_types` SET `street_type` = 'hegyhát köz';
REPLACE INTO `street_types` SET `street_type` = 'hídfő';
REPLACE INTO `street_types` SET `street_type` = 'hrsz.';
REPLACE INTO `street_types` SET `street_type` = 'iskola';
REPLACE INTO `street_types` SET `street_type` = 'játszótér';
REPLACE INTO `street_types` SET `street_type` = 'kapu';
REPLACE INTO `street_types` SET `street_type` = 'kastély';
REPLACE INTO `street_types` SET `street_type` = 'kert';
REPLACE INTO `street_types` SET `street_type` = 'kertsor';
REPLACE INTO `street_types` SET `street_type` = 'kilátó';
REPLACE INTO `street_types` SET `street_type` = 'kioszk';
REPLACE INTO `street_types` SET `street_type` = 'kocsiszín';
REPLACE INTO `street_types` SET `street_type` = 'kolónia';
REPLACE INTO `street_types` SET `street_type` = 'korzó';
REPLACE INTO `street_types` SET `street_type` = 'kör';
REPLACE INTO `street_types` SET `street_type` = 'körönd';
REPLACE INTO `street_types` SET `street_type` = 'körtér';
REPLACE INTO `street_types` SET `street_type` = 'körút';
REPLACE INTO `street_types` SET `street_type` = 'körvasútsor';
REPLACE INTO `street_types` SET `street_type` = 'körzet';
REPLACE INTO `street_types` SET `street_type` = 'kultúrpark';
REPLACE INTO `street_types` SET `street_type` = 'kunyhó';
REPLACE INTO `street_types` SET `street_type` = 'kút';
REPLACE INTO `street_types` SET `street_type` = 'kültelek';
REPLACE INTO `street_types` SET `street_type` = 'külterület';
REPLACE INTO `street_types` SET `street_type` = 'lakóház';
REPLACE INTO `street_types` SET `street_type` = 'lakónegyed';
REPLACE INTO `street_types` SET `street_type` = 'lakópark';
REPLACE INTO `street_types` SET `street_type` = 'lakótelep';
REPLACE INTO `street_types` SET `street_type` = 'lejáró';
REPLACE INTO `street_types` SET `street_type` = 'lejtő';
REPLACE INTO `street_types` SET `street_type` = 'lépcső';
REPLACE INTO `street_types` SET `street_type` = 'liget';
REPLACE INTO `street_types` SET `street_type` = 'major';
REPLACE INTO `street_types` SET `street_type` = 'malom';
REPLACE INTO `street_types` SET `street_type` = 'menedékház';
REPLACE INTO `street_types` SET `street_type` = 'mélyút';
REPLACE INTO `street_types` SET `street_type` = 'munkásszálló';
REPLACE INTO `street_types` SET `street_type` = 'műút';
REPLACE INTO `street_types` SET `street_type` = 'oldal';
REPLACE INTO `street_types` SET `street_type` = 'orom';
REPLACE INTO `street_types` SET `street_type` = 'őrház';
REPLACE INTO `street_types` SET `street_type` = 'őrházak';
REPLACE INTO `street_types` SET `street_type` = 'őrházlak';
REPLACE INTO `street_types` SET `street_type` = 'park';
REPLACE INTO `street_types` SET `street_type` = 'parkja';
REPLACE INTO `street_types` SET `street_type` = 'parkoló';
REPLACE INTO `street_types` SET `street_type` = 'part';
REPLACE INTO `street_types` SET `street_type` = 'pavilon';
REPLACE INTO `street_types` SET `street_type` = 'pálya';
REPLACE INTO `street_types` SET `street_type` = 'pályaudvar';
REPLACE INTO `street_types` SET `street_type` = 'piac';
REPLACE INTO `street_types` SET `street_type` = 'pihenő';
REPLACE INTO `street_types` SET `street_type` = 'pince';
REPLACE INTO `street_types` SET `street_type` = 'pincesor';
REPLACE INTO `street_types` SET `street_type` = 'postafiók';
REPLACE INTO `street_types` SET `street_type` = 'puszta';
REPLACE INTO `street_types` SET `street_type` = 'rakpart';
REPLACE INTO `street_types` SET `street_type` = 'repülőtér';
REPLACE INTO `street_types` SET `street_type` = 'rész';
REPLACE INTO `street_types` SET `street_type` = 'rét';
REPLACE INTO `street_types` SET `street_type` = 'sarok';
REPLACE INTO `street_types` SET `street_type` = 'sánc';
REPLACE INTO `street_types` SET `street_type` = 'sávház';
REPLACE INTO `street_types` SET `street_type` = 'sétány';
REPLACE INTO `street_types` SET `street_type` = 'sor';
REPLACE INTO `street_types` SET `street_type` = 'sora';
REPLACE INTO `street_types` SET `street_type` = 'sportpálya';
REPLACE INTO `street_types` SET `street_type` = 'sporttelep';
REPLACE INTO `street_types` SET `street_type` = 'stadion';
REPLACE INTO `street_types` SET `street_type` = 'strandfürdő';
REPLACE INTO `street_types` SET `street_type` = 'sugárút';
REPLACE INTO `street_types` SET `street_type` = 'szállás';
REPLACE INTO `street_types` SET `street_type` = 'szállások';
REPLACE INTO `street_types` SET `street_type` = 'szer';
REPLACE INTO `street_types` SET `street_type` = 'szél';
REPLACE INTO `street_types` SET `street_type` = 'sziget';
REPLACE INTO `street_types` SET `street_type` = 'szivattyútelep';
REPLACE INTO `street_types` SET `street_type` = 'szőlő';
REPLACE INTO `street_types` SET `street_type` = 'szőlőhegy';
REPLACE INTO `street_types` SET `street_type` = 'szőlők';
REPLACE INTO `street_types` SET `street_type` = 'tag';
REPLACE INTO `street_types` SET `street_type` = 'tanya';
REPLACE INTO `street_types` SET `street_type` = 'tanyák';
REPLACE INTO `street_types` SET `street_type` = 'telep';
REPLACE INTO `street_types` SET `street_type` = 'temető';
REPLACE INTO `street_types` SET `street_type` = 'tere';
REPLACE INTO `street_types` SET `street_type` = 'tető';
REPLACE INTO `street_types` SET `street_type` = 'téli kikötő';
REPLACE INTO `street_types` SET `street_type` = 'tömb';
REPLACE INTO `street_types` SET `street_type` = 'turistaház';
REPLACE INTO `street_types` SET `street_type` = 'udvar';
REPLACE INTO `street_types` SET `street_type` = 'utak';
REPLACE INTO `street_types` SET `street_type` = 'utcája';
REPLACE INTO `street_types` SET `street_type` = 'útja';
REPLACE INTO `street_types` SET `street_type` = 'útőrház';
REPLACE INTO `street_types` SET `street_type` = 'üdülő';
REPLACE INTO `street_types` SET `street_type` = 'üdülő-part';
REPLACE INTO `street_types` SET `street_type` = 'üdülő-sor';
REPLACE INTO `street_types` SET `street_type` = 'üdülő-telep';
REPLACE INTO `street_types` SET `street_type` = 'vadaskert';
REPLACE INTO `street_types` SET `street_type` = 'vadászház';
REPLACE INTO `street_types` SET `street_type` = 'vasútállomás';
REPLACE INTO `street_types` SET `street_type` = 'vasúti megálló';
REPLACE INTO `street_types` SET `street_type` = 'vasúti őrház';
REPLACE INTO `street_types` SET `street_type` = 'vasútsor';
REPLACE INTO `street_types` SET `street_type` = 'vágóhíd';
REPLACE INTO `street_types` SET `street_type` = 'vár';
REPLACE INTO `street_types` SET `street_type` = 'várköz';
REPLACE INTO `street_types` SET `street_type` = 'város';
REPLACE INTO `street_types` SET `street_type` = 'vezetőút';
REPLACE INTO `street_types` SET `street_type` = 'villasor';
REPLACE INTO `street_types` SET `street_type` = 'vízmű';
REPLACE INTO `street_types` SET `street_type` = 'völgy';
REPLACE INTO `street_types` SET `street_type` = 'zsilip';
REPLACE INTO `street_types` SET `street_type` = 'zug';
REPLACE INTO `street_types` SET `street_type` = 'út';
REPLACE INTO `street_types` SET `street_type` = 'utca';
REPLACE INTO `street_types` SET `street_type` = 'tér';
REPLACE INTO `street_types` SET `street_type` = 'köz';
REPLACE INTO `street_types` SET `street_type` = 'akna';
REPLACE INTO `street_types` SET `street_type` = 'akna-alsó';
REPLACE INTO `street_types` SET `street_type` = 'akna-felső';
REPLACE INTO `street_types` SET `street_type` = 'alagút';
REPLACE INTO `street_types` SET `street_type` = 'alsórakpart';
REPLACE INTO `street_types` SET `street_type` = 'arborétum';
REPLACE INTO `street_types` SET `street_type` = 'autóút';
REPLACE INTO `street_types` SET `street_type` = 'állat és növ.kert';
REPLACE INTO `street_types` SET `street_type` = 'állomás';
REPLACE INTO `street_types` SET `street_type` = 'árnyék';
REPLACE INTO `street_types` SET `street_type` = 'árok';
REPLACE INTO `street_types` SET `street_type` = 'átjáró';
REPLACE INTO `street_types` SET `street_type` = 'barakképület';
REPLACE INTO `street_types` SET `street_type` = 'barlang';
REPLACE INTO `street_types` SET `street_type` = 'bánya';
REPLACE INTO `street_types` SET `street_type` = 'bányatelep';
REPLACE INTO `street_types` SET `street_type` = 'bástya';
REPLACE INTO `street_types` SET `street_type` = 'bástyája';
REPLACE INTO `street_types` SET `street_type` = 'bejáró';
REPLACE INTO `street_types` SET `street_type` = 'bekötőút';
REPLACE INTO `street_types` SET `street_type` = 'csárda';
REPLACE INTO `street_types` SET `street_type` = 'csónakházak';
REPLACE INTO `street_types` SET `street_type` = 'domb';
REPLACE INTO `street_types` SET `street_type` = 'dűlő';
REPLACE INTO `street_types` SET `street_type` = 'dűlősor';
REPLACE INTO `street_types` SET `street_type` = 'dűlőterület';
REPLACE INTO `street_types` SET `street_type` = 'dűlőút';
REPLACE INTO `street_types` SET `street_type` = 'egyetemváros';
REPLACE INTO `street_types` SET `street_type` = 'egyéb';
REPLACE INTO `street_types` SET `street_type` = 'elágazás';
REPLACE INTO `street_types` SET `street_type` = 'emlékút';
REPLACE INTO `street_types` SET `street_type` = 'erdészház';
REPLACE INTO `street_types` SET `street_type` = 'erdészlak';
REPLACE INTO `street_types` SET `street_type` = 'erdő';
REPLACE INTO `street_types` SET `street_type` = 'erdősor';
REPLACE INTO `street_types` SET `street_type` = 'fasor';
REPLACE INTO `street_types` SET `street_type` = 'fasora';
REPLACE INTO `street_types` SET `street_type` = 'felső';
REPLACE INTO `street_types` SET `street_type` = 'forduló';
REPLACE INTO `street_types` SET `street_type` = 'föld';
REPLACE INTO `street_types` SET `street_type` = 'főmérnökség';
REPLACE INTO `street_types` SET `street_type` = 'főtér';
REPLACE INTO `street_types` SET `street_type` = 'főút';
REPLACE INTO `street_types` SET `street_type` = 'gát';
REPLACE INTO `street_types` SET `street_type` = 'gátőrház';
REPLACE INTO `street_types` SET `street_type` = 'gátsor';
REPLACE INTO `street_types` SET `street_type` = 'gyár';
REPLACE INTO `street_types` SET `street_type` = 'gyártelep';
REPLACE INTO `street_types` SET `street_type` = 'gyárváros';
REPLACE INTO `street_types` SET `street_type` = 'gyümölcsös';
REPLACE INTO `street_types` SET `street_type` = 'határsor';
REPLACE INTO `street_types` SET `street_type` = 'határút';
REPLACE INTO `street_types` SET `street_type` = 'ház';
REPLACE INTO `street_types` SET `street_type` = 'hegy';
REPLACE INTO `street_types` SET `street_type` = 'hegyhát';
REPLACE INTO `street_types` SET `street_type` = 'hegyhát dűlő';
REPLACE INTO `street_types` SET `street_type` = 'hegyhát köz';
REPLACE INTO `street_types` SET `street_type` = 'hídfő';
REPLACE INTO `street_types` SET `street_type` = 'hrsz.';
REPLACE INTO `street_types` SET `street_type` = 'iskola';
REPLACE INTO `street_types` SET `street_type` = 'játszótér';
REPLACE INTO `street_types` SET `street_type` = 'kapu';
REPLACE INTO `street_types` SET `street_type` = 'kastély';
REPLACE INTO `street_types` SET `street_type` = 'kert';
REPLACE INTO `street_types` SET `street_type` = 'kertsor';
REPLACE INTO `street_types` SET `street_type` = 'kilátó';
REPLACE INTO `street_types` SET `street_type` = 'kioszk';
REPLACE INTO `street_types` SET `street_type` = 'kocsiszín';
REPLACE INTO `street_types` SET `street_type` = 'kolónia';
REPLACE INTO `street_types` SET `street_type` = 'korzó';
REPLACE INTO `street_types` SET `street_type` = 'kör';
REPLACE INTO `street_types` SET `street_type` = 'körönd';
REPLACE INTO `street_types` SET `street_type` = 'körtér';
REPLACE INTO `street_types` SET `street_type` = 'körút';
REPLACE INTO `street_types` SET `street_type` = 'körvasútsor';
REPLACE INTO `street_types` SET `street_type` = 'körzet';
REPLACE INTO `street_types` SET `street_type` = 'kultúrpark';
REPLACE INTO `street_types` SET `street_type` = 'kunyhó';
REPLACE INTO `street_types` SET `street_type` = 'kút';
REPLACE INTO `street_types` SET `street_type` = 'kültelek';
REPLACE INTO `street_types` SET `street_type` = 'külterület';
REPLACE INTO `street_types` SET `street_type` = 'lakóház';
REPLACE INTO `street_types` SET `street_type` = 'lakónegyed';
REPLACE INTO `street_types` SET `street_type` = 'lakópark';
REPLACE INTO `street_types` SET `street_type` = 'lakótelep';
REPLACE INTO `street_types` SET `street_type` = 'lejáró';
REPLACE INTO `street_types` SET `street_type` = 'lejtő';
REPLACE INTO `street_types` SET `street_type` = 'lépcső';
REPLACE INTO `street_types` SET `street_type` = 'liget';
REPLACE INTO `street_types` SET `street_type` = 'major';
REPLACE INTO `street_types` SET `street_type` = 'malom';
REPLACE INTO `street_types` SET `street_type` = 'menedékház';
REPLACE INTO `street_types` SET `street_type` = 'mélyút';
REPLACE INTO `street_types` SET `street_type` = 'munkásszálló';
REPLACE INTO `street_types` SET `street_type` = 'műút';
REPLACE INTO `street_types` SET `street_type` = 'oldal';
REPLACE INTO `street_types` SET `street_type` = 'orom';
REPLACE INTO `street_types` SET `street_type` = 'őrház';
REPLACE INTO `street_types` SET `street_type` = 'őrházak';
REPLACE INTO `street_types` SET `street_type` = 'őrházlak';
REPLACE INTO `street_types` SET `street_type` = 'park';
REPLACE INTO `street_types` SET `street_type` = 'parkja';
REPLACE INTO `street_types` SET `street_type` = 'parkoló';
REPLACE INTO `street_types` SET `street_type` = 'part';
REPLACE INTO `street_types` SET `street_type` = 'pavilon';
REPLACE INTO `street_types` SET `street_type` = 'pálya';
REPLACE INTO `street_types` SET `street_type` = 'pályaudvar';
REPLACE INTO `street_types` SET `street_type` = 'piac';
REPLACE INTO `street_types` SET `street_type` = 'pihenő';
REPLACE INTO `street_types` SET `street_type` = 'pince';
REPLACE INTO `street_types` SET `street_type` = 'pincesor';
REPLACE INTO `street_types` SET `street_type` = 'postafiók';
REPLACE INTO `street_types` SET `street_type` = 'puszta';
REPLACE INTO `street_types` SET `street_type` = 'rakpart';
REPLACE INTO `street_types` SET `street_type` = 'repülőtér';
REPLACE INTO `street_types` SET `street_type` = 'rész';
REPLACE INTO `street_types` SET `street_type` = 'rét';
REPLACE INTO `street_types` SET `street_type` = 'sarok';
REPLACE INTO `street_types` SET `street_type` = 'sánc';
REPLACE INTO `street_types` SET `street_type` = 'sávház';
REPLACE INTO `street_types` SET `street_type` = 'sétány';
REPLACE INTO `street_types` SET `street_type` = 'sor';
REPLACE INTO `street_types` SET `street_type` = 'sora';
REPLACE INTO `street_types` SET `street_type` = 'sportpálya';
REPLACE INTO `street_types` SET `street_type` = 'sporttelep';
REPLACE INTO `street_types` SET `street_type` = 'stadion';
REPLACE INTO `street_types` SET `street_type` = 'strandfürdő';
REPLACE INTO `street_types` SET `street_type` = 'sugárút';
REPLACE INTO `street_types` SET `street_type` = 'szállás';
REPLACE INTO `street_types` SET `street_type` = 'szállások';
REPLACE INTO `street_types` SET `street_type` = 'szer';
REPLACE INTO `street_types` SET `street_type` = 'szél';
REPLACE INTO `street_types` SET `street_type` = 'sziget';
REPLACE INTO `street_types` SET `street_type` = 'szivattyútelep';
REPLACE INTO `street_types` SET `street_type` = 'szőlő';
REPLACE INTO `street_types` SET `street_type` = 'szőlőhegy';
REPLACE INTO `street_types` SET `street_type` = 'szőlők';
REPLACE INTO `street_types` SET `street_type` = 'tag';
REPLACE INTO `street_types` SET `street_type` = 'tanya';
REPLACE INTO `street_types` SET `street_type` = 'tanyák';
REPLACE INTO `street_types` SET `street_type` = 'telep';
REPLACE INTO `street_types` SET `street_type` = 'temető';
REPLACE INTO `street_types` SET `street_type` = 'tere';
REPLACE INTO `street_types` SET `street_type` = 'tető';
REPLACE INTO `street_types` SET `street_type` = 'téli kikötő';
REPLACE INTO `street_types` SET `street_type` = 'tömb';
REPLACE INTO `street_types` SET `street_type` = 'turistaház';
REPLACE INTO `street_types` SET `street_type` = 'udvar';
REPLACE INTO `street_types` SET `street_type` = 'utak';
REPLACE INTO `street_types` SET `street_type` = 'utcája';
REPLACE INTO `street_types` SET `street_type` = 'útja';
REPLACE INTO `street_types` SET `street_type` = 'útőrház';
REPLACE INTO `street_types` SET `street_type` = 'üdülő';
REPLACE INTO `street_types` SET `street_type` = 'üdülő-part';
REPLACE INTO `street_types` SET `street_type` = 'üdülő-sor';
REPLACE INTO `street_types` SET `street_type` = 'üdülő-telep';
REPLACE INTO `street_types` SET `street_type` = 'vadaskert';
REPLACE INTO `street_types` SET `street_type` = 'vadászház';
REPLACE INTO `street_types` SET `street_type` = 'vasútállomás';
REPLACE INTO `street_types` SET `street_type` = 'vasúti megálló';
REPLACE INTO `street_types` SET `street_type` = 'vasúti őrház';
REPLACE INTO `street_types` SET `street_type` = 'vasútsor';
REPLACE INTO `street_types` SET `street_type` = 'vágóhíd';
REPLACE INTO `street_types` SET `street_type` = 'vár';
REPLACE INTO `street_types` SET `street_type` = 'várköz';
REPLACE INTO `street_types` SET `street_type` = 'város';
REPLACE INTO `street_types` SET `street_type` = 'vezetőút';
REPLACE INTO `street_types` SET `street_type` = 'villasor';
REPLACE INTO `street_types` SET `street_type` = 'vízmű';
REPLACE INTO `street_types` SET `street_type` = 'völgy';
REPLACE INTO `street_types` SET `street_type` = 'zsilip';
REPLACE INTO `street_types` SET `street_type` = 'zug';