
--select * from users;

--delete from users;

--select 'ADmin123@' REGEXP '^(?=.*[A-Z].*[A-Z])(?=.*[!@#$&*])(?=.*[0-9].*[0-9])(?=.*[a-z].*[a-z]).{8}$';


--select 'ADmin123@!+$"%/=' REGEXP '^(?=.*([A-Z]){1,})(?=.*[!-@]{1,})(?=.*[0-9]{1,})(?=.*[a-z]{1,}).{8,100}$';

DELETE FROM nationality_marks;

Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('AFG','Afganisztán');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('AG','Antigua és Barbuda');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('AL','Albánia');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('AM','Örményország');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('ANG','Angola');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('AND','Andorra');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('AUS','Ausztrália (és külbirtokai)');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('AZ','Azerbajdzsán');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('BD','Banglades');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('BDS','Barbados');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('BER','Bermuda');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('BF','Burkina Faso');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('BHT','Bhután');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('BOL','Bolívia');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('BR','Brazília');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('BRN','Bahrein');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('BRU','Brunei');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('BS','Bahama-szigetek');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('BU','Burundi');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('BW','Botswana');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('BY','Fehéroroszország (Belarusz)');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('BZ','Belize');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('C','Kuba');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('CAM','Kamerun');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('CC', 'Konzulátusi testület');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('CD', 'Diplomáciai testület');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('CI','Elefántcsontpart');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('CL','Srí Lanka');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('CO','Kolumbia');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('COM','Comore-szigetek');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('CR','Costa Rica');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('CV','Zöld-foki Köztársaság');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('CY','Ciprus');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('DJ','Dzsibuti');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('DOM','Dominikai Köztársaság');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('DPR', 'Észak-Korea');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('DRC','Kongói Demokratikus Köztársaság (Zaire)');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('DY','Benin');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('DZ','Algéria');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('EAK','Kenya');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('EAT','Tanzánia');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('EAU','Uganda');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('EC','Ecuador');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('ER','Eritrea');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('ES','El Salvador');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('EST','Észtország');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('ET','Egyiptom    ');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('ETH','Etiópia');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('EUR','Európai Unió hivatali gépjárművek');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('FJI','Fidzsi-szigetek');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('FL','Liechtenstein');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('FO','Feröer');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('FSM','Mikronézia');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('G','Gabon');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('GBA', 'Alderney Alderney (Guernsey)');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('GBG','Guernsey');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('GBJ','Jersey');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('GBM','Man');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('GBZ','Gibraltár');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('GCA','Guatemala');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('GE','Grúzia');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('GH','Ghána');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('GUY','Guyana');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('HK','Hongkong');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('HKJ','Jordánia');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('HN','Honduras');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('IND','India');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('IR','Irán');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('IRL','Írország');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('IRQ','Irak');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('IS','Izland');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('J','Japán');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('JA','Jamaica');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('K','Kambodzsa');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('KIR','Kiribati');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('KN','Saint Kitts és Nevis');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('KS','Kirgizisztán');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('KWT','Kuvait');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('KZ','Kazahsztán');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('LAO','Laosz');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('LAR','Líbia');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('LB','Libéria');
Insert into nationality_marks ( nationality_mark, nationality_mark_name) VALUES ('LS','Lesotho');
