-- Active: 1678652479984@@127.0.0.1@3306@weighing_db

USE WEIGHING_DB;
SET autocommit = 1;

-- REPLACE INTO `PERMISSIONS` SET permission_id = 'A', `permission` = 'Adat megtekintés';
-- REPLACE INTO `PERMISSIONS` SET permission_id = 'M', `permission` = 'Mérés készítés';
-- REPLACE INTO `PERMISSIONS` SET permission_id = 'T', `permission` = 'Törzsadat kezelés';
-- REPLACE INTO `PERMISSIONS` SET permission_id = 'F', `permission` = 'Felhasználó kezelés';
-- REPLACE INTO `PERMISSIONS` SET permission_id = 'B', `permission` = 'Beállítás kezelés';

DELETE FROM measurement_types;
REPLACE INTO `measurement_types` SET id = 'M', `name` = 'Mérlegelt adat' ;
REPLACE INTO `measurement_types` SET id = 'K', `name` = 'Kézzel megadott';
REPLACE INTO `measurement_types` SET id = 'G', `name` = 'Gépjármű tárolt súlya';

DELETE FROM movements;
REPLACE INTO `movements` SET `name` = 'Beszállítás', `stock_relation`= '+', `head` = 'MÉRLEGJEGY', `left_side` = 'átvevő', `right_side` = 'átadó', `form_file_name` = 'merlegjegy.html';
REPLACE INTO `movements` SET `name` = 'Kiszállítás', `stock_relation`= '-', `head` = 'SZÁLLÍTÓLEVÉL', `left_side` = 'átadó', `right_side` = 'átvevő', `form_file_name` = 'szallito.html';
REPLACE INTO `movements` SET `name` = 'Csak mérés', `stock_relation`= ' ', `head` = 'MÉRLEGELÉS', `left_side` = '', `right_side` = '', `form_file_name` = 'merlegeles.html';
REPLACE INTO `movements` SET `name` = 'Induló készlet', `stock_relation`= '+', `head` = 'INDULÓ KÉSZLET', `left_side` = 'átvevő', `right_side` = 'átadó', `form_file_name` = 'merlegjegy.html';
REPLACE INTO `movements` SET `name` = 'Selejtezés', `stock_relation`= '-', `head` = 'SELEJTEZÉS MÉRLEGJEGY', `left_side` = 'átvevő', `right_side` = 'átadó', `form_file_name` = 'merlegjegy.html';
REPLACE INTO `movements` SET `name` = 'Többlet készlet', `stock_relation`= '+', `head` = 'TÖBBLET LELTÁR KÉSZLET', `left_side` = 'átvevő', `right_side` = 'átadó', `form_file_name` = 'merlegjegy.html';
REPLACE INTO `movements` SET `name` = 'Leltár hiány', `stock_relation`= '-', `head` = 'LELTÁR HIÁNY MÉRLEGJEGY', `left_side` = 'átvevő', `right_side` = 'átadó', `form_file_name` = 'merlegjegy.html';

DELETE FROM countries;
REPLACE INTO `countries` SET code = 'HU', name = 'Magyarország';
REPLACE INTO `countries` SET code = 'AT', name = 'Ausztria';
REPLACE INTO `countries` SET code = 'BA', name = 'Bosznia-Hercegovina';
REPLACE INTO `countries` SET code = 'BE', name = 'Belgium';
REPLACE INTO `countries` SET code = 'BG', name = 'Bulgária';
REPLACE INTO `countries` SET code = 'CY', name = 'Ciprus';
REPLACE INTO `countries` SET code = 'CZ', name = 'Cseh Köztársaság';
REPLACE INTO `countries` SET code = 'DK', name = 'Dánia';
REPLACE INTO `countries` SET code = 'US', name = 'Egyesült Államok';
REPLACE INTO `countries` SET code = 'GB', name = 'Egyesült Királyság';
REPLACE INTO `countries` SET code = 'EE', name = 'Észtország';
REPLACE INTO `countries` SET code = 'FI', name = 'Finnország';
REPLACE INTO `countries` SET code = 'FR', name = 'Franciaország';
REPLACE INTO `countries` SET code = 'GR', name = 'Görögország';
REPLACE INTO `countries` SET code = 'NL', name = 'Hollandia';
REPLACE INTO `countries` SET code = 'HR', name = 'Horvátország';
REPLACE INTO `countries` SET code = 'IE', name = 'Írország';
REPLACE INTO `countries` SET code = 'PL', name = 'Lengyelország';
REPLACE INTO `countries` SET code = 'LV', name = 'Lettország';
REPLACE INTO `countries` SET code = 'LT', name = 'Litvánia';
REPLACE INTO `countries` SET code = 'LU', name = 'Luxemburg';
REPLACE INTO `countries` SET code = 'MT', name = 'Málta';
REPLACE INTO `countries` SET code = 'DE', name = 'Németország';
REPLACE INTO `countries` SET code = 'IT', name = 'Olaszország';
REPLACE INTO `countries` SET code = 'PT', name = 'Portugália';
REPLACE INTO `countries` SET code = 'RO', name = 'Románia';
REPLACE INTO `countries` SET code = 'ES', name = 'Spanyolország';
REPLACE INTO `countries` SET code = 'CH', name = 'Svájc';
REPLACE INTO `countries` SET code = 'SE', name = 'Svédor;szág';
REPLACE INTO `countries` SET code = 'XS', name = 'Szerbia';
REPLACE INTO `countries` SET code = 'SK', name = 'Szlovákia';
REPLACE INTO `countries` SET code = 'SI', name = 'Szlovénia';
REPLACE INTO `countries` SET code = 'UK', name = 'Ukrajna';

DELETE FROM street_types;
REPLACE INTO `street_types` SET `street_type` = 'út';
REPLACE INTO `street_types` SET `street_type` = 'utca';
REPLACE INTO `street_types` SET `street_type` = 'tér';
REPLACE INTO `street_types` SET `street_type` = 'köz';
REPLACE INTO `street_types` SET `street_type` = 'akna';
REPLACE INTO `street_types` SET `street_type` = 'akna-alsó';
REPLACE INTO `street_types` SET `street_type` = 'akna-felső';
REPLACE INTO `street_types` SET `street_type` = 'alagút';
REPLACE INTO `street_types` SET `street_type` = 'alsórakpart';
REPLACE INTO `street_types` SET `street_type` = 'arborétum';
REPLACE INTO `street_types` SET `street_type` = 'autóút';
REPLACE INTO `street_types` SET `street_type` = 'állat és növ.kert';
REPLACE INTO `street_types` SET `street_type` = 'állomás';
REPLACE INTO `street_types` SET `street_type` = 'árnyék';
REPLACE INTO `street_types` SET `street_type` = 'árok';
REPLACE INTO `street_types` SET `street_type` = 'átjáró';
REPLACE INTO `street_types` SET `street_type` = 'barakképület';
REPLACE INTO `street_types` SET `street_type` = 'barlang';
REPLACE INTO `street_types` SET `street_type` = 'bánya';
REPLACE INTO `street_types` SET `street_type` = 'bányatelep';
REPLACE INTO `street_types` SET `street_type` = 'bástya';
REPLACE INTO `street_types` SET `street_type` = 'bástyája';
REPLACE INTO `street_types` SET `street_type` = 'bejáró';
REPLACE INTO `street_types` SET `street_type` = 'bekötőút';
REPLACE INTO `street_types` SET `street_type` = 'csárda';
REPLACE INTO `street_types` SET `street_type` = 'csónakházak';
REPLACE INTO `street_types` SET `street_type` = 'domb';
REPLACE INTO `street_types` SET `street_type` = 'dűlő';
REPLACE INTO `street_types` SET `street_type` = 'dűlősor';
REPLACE INTO `street_types` SET `street_type` = 'dűlőterület';
REPLACE INTO `street_types` SET `street_type` = 'dűlőút';
REPLACE INTO `street_types` SET `street_type` = 'egyetemváros';
REPLACE INTO `street_types` SET `street_type` = 'egyéb';
REPLACE INTO `street_types` SET `street_type` = 'elágazás';
REPLACE INTO `street_types` SET `street_type` = 'emlékút';
REPLACE INTO `street_types` SET `street_type` = 'erdészház';
REPLACE INTO `street_types` SET `street_type` = 'erdészlak';
REPLACE INTO `street_types` SET `street_type` = 'erdő';
REPLACE INTO `street_types` SET `street_type` = 'erdősor';
REPLACE INTO `street_types` SET `street_type` = 'fasor';
REPLACE INTO `street_types` SET `street_type` = 'fasora';
REPLACE INTO `street_types` SET `street_type` = 'felső';
REPLACE INTO `street_types` SET `street_type` = 'forduló';
REPLACE INTO `street_types` SET `street_type` = 'föld';
REPLACE INTO `street_types` SET `street_type` = 'főmérnökség';
REPLACE INTO `street_types` SET `street_type` = 'főtér';
REPLACE INTO `street_types` SET `street_type` = 'főút';
REPLACE INTO `street_types` SET `street_type` = 'gát';
REPLACE INTO `street_types` SET `street_type` = 'gátőrház';
REPLACE INTO `street_types` SET `street_type` = 'gátsor';
REPLACE INTO `street_types` SET `street_type` = 'gyár';
REPLACE INTO `street_types` SET `street_type` = 'gyártelep';
REPLACE INTO `street_types` SET `street_type` = 'gyárváros';
REPLACE INTO `street_types` SET `street_type` = 'gyümölcsös';
REPLACE INTO `street_types` SET `street_type` = 'határsor';
REPLACE INTO `street_types` SET `street_type` = 'határút';
REPLACE INTO `street_types` SET `street_type` = 'ház';
REPLACE INTO `street_types` SET `street_type` = 'hegy';
REPLACE INTO `street_types` SET `street_type` = 'hegyhát';
REPLACE INTO `street_types` SET `street_type` = 'hegyhát dűlő';
REPLACE INTO `street_types` SET `street_type` = 'hegyhát köz';
REPLACE INTO `street_types` SET `street_type` = 'hídfő';
REPLACE INTO `street_types` SET `street_type` = 'hrsz.';
REPLACE INTO `street_types` SET `street_type` = 'iskola';
REPLACE INTO `street_types` SET `street_type` = 'játszótér';
REPLACE INTO `street_types` SET `street_type` = 'kapu';
REPLACE INTO `street_types` SET `street_type` = 'kastély';
REPLACE INTO `street_types` SET `street_type` = 'kert';
REPLACE INTO `street_types` SET `street_type` = 'kertsor';
REPLACE INTO `street_types` SET `street_type` = 'kilátó';
REPLACE INTO `street_types` SET `street_type` = 'kioszk';
REPLACE INTO `street_types` SET `street_type` = 'kocsiszín';
REPLACE INTO `street_types` SET `street_type` = 'kolónia';
REPLACE INTO `street_types` SET `street_type` = 'korzó';
REPLACE INTO `street_types` SET `street_type` = 'kör';
REPLACE INTO `street_types` SET `street_type` = 'körönd';
REPLACE INTO `street_types` SET `street_type` = 'körtér';
REPLACE INTO `street_types` SET `street_type` = 'körút';
REPLACE INTO `street_types` SET `street_type` = 'körvasútsor';
REPLACE INTO `street_types` SET `street_type` = 'körzet';
REPLACE INTO `street_types` SET `street_type` = 'kultúrpark';
REPLACE INTO `street_types` SET `street_type` = 'kunyhó';
REPLACE INTO `street_types` SET `street_type` = 'kút';
REPLACE INTO `street_types` SET `street_type` = 'kültelek';
REPLACE INTO `street_types` SET `street_type` = 'külterület';
REPLACE INTO `street_types` SET `street_type` = 'lakóház';
REPLACE INTO `street_types` SET `street_type` = 'lakónegyed';
REPLACE INTO `street_types` SET `street_type` = 'lakópark';
REPLACE INTO `street_types` SET `street_type` = 'lakótelep';
REPLACE INTO `street_types` SET `street_type` = 'lejáró';
REPLACE INTO `street_types` SET `street_type` = 'lejtő';
REPLACE INTO `street_types` SET `street_type` = 'lépcső';
REPLACE INTO `street_types` SET `street_type` = 'liget';
REPLACE INTO `street_types` SET `street_type` = 'major';
REPLACE INTO `street_types` SET `street_type` = 'malom';
REPLACE INTO `street_types` SET `street_type` = 'menedékház';
REPLACE INTO `street_types` SET `street_type` = 'mélyút';
REPLACE INTO `street_types` SET `street_type` = 'munkásszálló';
REPLACE INTO `street_types` SET `street_type` = 'műút';
REPLACE INTO `street_types` SET `street_type` = 'oldal';
REPLACE INTO `street_types` SET `street_type` = 'orom';
REPLACE INTO `street_types` SET `street_type` = 'őrház';
REPLACE INTO `street_types` SET `street_type` = 'őrházak';
REPLACE INTO `street_types` SET `street_type` = 'őrházlak';
REPLACE INTO `street_types` SET `street_type` = 'park';
REPLACE INTO `street_types` SET `street_type` = 'parkja';
REPLACE INTO `street_types` SET `street_type` = 'parkoló';
REPLACE INTO `street_types` SET `street_type` = 'part';
REPLACE INTO `street_types` SET `street_type` = 'pavilon';
REPLACE INTO `street_types` SET `street_type` = 'pálya';
REPLACE INTO `street_types` SET `street_type` = 'pályaudvar';
REPLACE INTO `street_types` SET `street_type` = 'piac';
REPLACE INTO `street_types` SET `street_type` = 'pihenő';
REPLACE INTO `street_types` SET `street_type` = 'pince';
REPLACE INTO `street_types` SET `street_type` = 'pincesor';
REPLACE INTO `street_types` SET `street_type` = 'postafiók';
REPLACE INTO `street_types` SET `street_type` = 'puszta';
REPLACE INTO `street_types` SET `street_type` = 'rakpart';
REPLACE INTO `street_types` SET `street_type` = 'repülőtér';
REPLACE INTO `street_types` SET `street_type` = 'rész';
REPLACE INTO `street_types` SET `street_type` = 'rét';
REPLACE INTO `street_types` SET `street_type` = 'sarok';
REPLACE INTO `street_types` SET `street_type` = 'sánc';
REPLACE INTO `street_types` SET `street_type` = 'sávház';
REPLACE INTO `street_types` SET `street_type` = 'sétány';
REPLACE INTO `street_types` SET `street_type` = 'sor';
REPLACE INTO `street_types` SET `street_type` = 'sora';
REPLACE INTO `street_types` SET `street_type` = 'sportpálya';
REPLACE INTO `street_types` SET `street_type` = 'sporttelep';
REPLACE INTO `street_types` SET `street_type` = 'stadion';
REPLACE INTO `street_types` SET `street_type` = 'strandfürdő';
REPLACE INTO `street_types` SET `street_type` = 'sugárút';
REPLACE INTO `street_types` SET `street_type` = 'szállás';
REPLACE INTO `street_types` SET `street_type` = 'szállások';
REPLACE INTO `street_types` SET `street_type` = 'szer';
REPLACE INTO `street_types` SET `street_type` = 'szél';
REPLACE INTO `street_types` SET `street_type` = 'sziget';
REPLACE INTO `street_types` SET `street_type` = 'szivattyútelep';
REPLACE INTO `street_types` SET `street_type` = 'szőlő';
REPLACE INTO `street_types` SET `street_type` = 'szőlőhegy';
REPLACE INTO `street_types` SET `street_type` = 'szőlők';
REPLACE INTO `street_types` SET `street_type` = 'tag';
REPLACE INTO `street_types` SET `street_type` = 'tanya';
REPLACE INTO `street_types` SET `street_type` = 'tanyák';
REPLACE INTO `street_types` SET `street_type` = 'telep';
REPLACE INTO `street_types` SET `street_type` = 'temető';
REPLACE INTO `street_types` SET `street_type` = 'tere';
REPLACE INTO `street_types` SET `street_type` = 'tető';
REPLACE INTO `street_types` SET `street_type` = 'téli kikötő';
REPLACE INTO `street_types` SET `street_type` = 'tömb';
REPLACE INTO `street_types` SET `street_type` = 'turistaház';
REPLACE INTO `street_types` SET `street_type` = 'udvar';
REPLACE INTO `street_types` SET `street_type` = 'utak';
REPLACE INTO `street_types` SET `street_type` = 'utcája';
REPLACE INTO `street_types` SET `street_type` = 'útja';
REPLACE INTO `street_types` SET `street_type` = 'útőrház';
REPLACE INTO `street_types` SET `street_type` = 'üdülő';
REPLACE INTO `street_types` SET `street_type` = 'üdülő-part';
REPLACE INTO `street_types` SET `street_type` = 'üdülő-sor';
REPLACE INTO `street_types` SET `street_type` = 'üdülő-telep';
REPLACE INTO `street_types` SET `street_type` = 'vadaskert';
REPLACE INTO `street_types` SET `street_type` = 'vadászház';
REPLACE INTO `street_types` SET `street_type` = 'vasútállomás';
REPLACE INTO `street_types` SET `street_type` = 'vasúti megálló';
REPLACE INTO `street_types` SET `street_type` = 'vasúti őrház';
REPLACE INTO `street_types` SET `street_type` = 'vasútsor';
REPLACE INTO `street_types` SET `street_type` = 'vágóhíd';
REPLACE INTO `street_types` SET `street_type` = 'vár';
REPLACE INTO `street_types` SET `street_type` = 'várköz';
REPLACE INTO `street_types` SET `street_type` = 'város';
REPLACE INTO `street_types` SET `street_type` = 'vezetőút';
REPLACE INTO `street_types` SET `street_type` = 'villasor';
REPLACE INTO `street_types` SET `street_type` = 'vízmű';
REPLACE INTO `street_types` SET `street_type` = 'völgy';
REPLACE INTO `street_types` SET `street_type` = 'zsilip';
REPLACE INTO `street_types` SET `street_type` = 'zug';
REPLACE INTO `street_types` SET `street_type` = 'út';
REPLACE INTO `street_types` SET `street_type` = 'utca';
REPLACE INTO `street_types` SET `street_type` = 'tér';
REPLACE INTO `street_types` SET `street_type` = 'köz';
REPLACE INTO `street_types` SET `street_type` = 'akna';
REPLACE INTO `street_types` SET `street_type` = 'akna-alsó';
REPLACE INTO `street_types` SET `street_type` = 'akna-felső';
REPLACE INTO `street_types` SET `street_type` = 'alagút';
REPLACE INTO `street_types` SET `street_type` = 'alsórakpart';
REPLACE INTO `street_types` SET `street_type` = 'arborétum';
REPLACE INTO `street_types` SET `street_type` = 'autóút';
REPLACE INTO `street_types` SET `street_type` = 'állat és növ.kert';
REPLACE INTO `street_types` SET `street_type` = 'állomás';
REPLACE INTO `street_types` SET `street_type` = 'árnyék';
REPLACE INTO `street_types` SET `street_type` = 'árok';
REPLACE INTO `street_types` SET `street_type` = 'átjáró';
REPLACE INTO `street_types` SET `street_type` = 'barakképület';
REPLACE INTO `street_types` SET `street_type` = 'barlang';
REPLACE INTO `street_types` SET `street_type` = 'bánya';
REPLACE INTO `street_types` SET `street_type` = 'bányatelep';
REPLACE INTO `street_types` SET `street_type` = 'bástya';
REPLACE INTO `street_types` SET `street_type` = 'bástyája';
REPLACE INTO `street_types` SET `street_type` = 'bejáró';
REPLACE INTO `street_types` SET `street_type` = 'bekötőút';
REPLACE INTO `street_types` SET `street_type` = 'csárda';
REPLACE INTO `street_types` SET `street_type` = 'csónakházak';
REPLACE INTO `street_types` SET `street_type` = 'domb';
REPLACE INTO `street_types` SET `street_type` = 'dűlő';
REPLACE INTO `street_types` SET `street_type` = 'dűlősor';
REPLACE INTO `street_types` SET `street_type` = 'dűlőterület';
REPLACE INTO `street_types` SET `street_type` = 'dűlőút';
REPLACE INTO `street_types` SET `street_type` = 'egyetemváros';
REPLACE INTO `street_types` SET `street_type` = 'egyéb';
REPLACE INTO `street_types` SET `street_type` = 'elágazás';
REPLACE INTO `street_types` SET `street_type` = 'emlékút';
REPLACE INTO `street_types` SET `street_type` = 'erdészház';
REPLACE INTO `street_types` SET `street_type` = 'erdészlak';
REPLACE INTO `street_types` SET `street_type` = 'erdő';
REPLACE INTO `street_types` SET `street_type` = 'erdősor';
REPLACE INTO `street_types` SET `street_type` = 'fasor';
REPLACE INTO `street_types` SET `street_type` = 'fasora';
REPLACE INTO `street_types` SET `street_type` = 'felső';
REPLACE INTO `street_types` SET `street_type` = 'forduló';
REPLACE INTO `street_types` SET `street_type` = 'föld';
REPLACE INTO `street_types` SET `street_type` = 'főmérnökség';
REPLACE INTO `street_types` SET `street_type` = 'főtér';
REPLACE INTO `street_types` SET `street_type` = 'főút';
REPLACE INTO `street_types` SET `street_type` = 'gát';
REPLACE INTO `street_types` SET `street_type` = 'gátőrház';
REPLACE INTO `street_types` SET `street_type` = 'gátsor';
REPLACE INTO `street_types` SET `street_type` = 'gyár';
REPLACE INTO `street_types` SET `street_type` = 'gyártelep';
REPLACE INTO `street_types` SET `street_type` = 'gyárváros';
REPLACE INTO `street_types` SET `street_type` = 'gyümölcsös';
REPLACE INTO `street_types` SET `street_type` = 'határsor';
REPLACE INTO `street_types` SET `street_type` = 'határút';
REPLACE INTO `street_types` SET `street_type` = 'ház';
REPLACE INTO `street_types` SET `street_type` = 'hegy';
REPLACE INTO `street_types` SET `street_type` = 'hegyhát';
REPLACE INTO `street_types` SET `street_type` = 'hegyhát dűlő';
REPLACE INTO `street_types` SET `street_type` = 'hegyhát köz';
REPLACE INTO `street_types` SET `street_type` = 'hídfő';
REPLACE INTO `street_types` SET `street_type` = 'hrsz.';
REPLACE INTO `street_types` SET `street_type` = 'iskola';
REPLACE INTO `street_types` SET `street_type` = 'játszótér';
REPLACE INTO `street_types` SET `street_type` = 'kapu';
REPLACE INTO `street_types` SET `street_type` = 'kastély';
REPLACE INTO `street_types` SET `street_type` = 'kert';
REPLACE INTO `street_types` SET `street_type` = 'kertsor';
REPLACE INTO `street_types` SET `street_type` = 'kilátó';
REPLACE INTO `street_types` SET `street_type` = 'kioszk';
REPLACE INTO `street_types` SET `street_type` = 'kocsiszín';
REPLACE INTO `street_types` SET `street_type` = 'kolónia';
REPLACE INTO `street_types` SET `street_type` = 'korzó';
REPLACE INTO `street_types` SET `street_type` = 'kör';
REPLACE INTO `street_types` SET `street_type` = 'körönd';
REPLACE INTO `street_types` SET `street_type` = 'körtér';
REPLACE INTO `street_types` SET `street_type` = 'körút';
REPLACE INTO `street_types` SET `street_type` = 'körvasútsor';
REPLACE INTO `street_types` SET `street_type` = 'körzet';
REPLACE INTO `street_types` SET `street_type` = 'kultúrpark';
REPLACE INTO `street_types` SET `street_type` = 'kunyhó';
REPLACE INTO `street_types` SET `street_type` = 'kút';
REPLACE INTO `street_types` SET `street_type` = 'kültelek';
REPLACE INTO `street_types` SET `street_type` = 'külterület';
REPLACE INTO `street_types` SET `street_type` = 'lakóház';
REPLACE INTO `street_types` SET `street_type` = 'lakónegyed';
REPLACE INTO `street_types` SET `street_type` = 'lakópark';
REPLACE INTO `street_types` SET `street_type` = 'lakótelep';
REPLACE INTO `street_types` SET `street_type` = 'lejáró';
REPLACE INTO `street_types` SET `street_type` = 'lejtő';
REPLACE INTO `street_types` SET `street_type` = 'lépcső';
REPLACE INTO `street_types` SET `street_type` = 'liget';
REPLACE INTO `street_types` SET `street_type` = 'major';
REPLACE INTO `street_types` SET `street_type` = 'malom';
REPLACE INTO `street_types` SET `street_type` = 'menedékház';
REPLACE INTO `street_types` SET `street_type` = 'mélyút';
REPLACE INTO `street_types` SET `street_type` = 'munkásszálló';
REPLACE INTO `street_types` SET `street_type` = 'műút';
REPLACE INTO `street_types` SET `street_type` = 'oldal';
REPLACE INTO `street_types` SET `street_type` = 'orom';
REPLACE INTO `street_types` SET `street_type` = 'őrház';
REPLACE INTO `street_types` SET `street_type` = 'őrházak';
REPLACE INTO `street_types` SET `street_type` = 'őrházlak';
REPLACE INTO `street_types` SET `street_type` = 'park';
REPLACE INTO `street_types` SET `street_type` = 'parkja';
REPLACE INTO `street_types` SET `street_type` = 'parkoló';
REPLACE INTO `street_types` SET `street_type` = 'part';
REPLACE INTO `street_types` SET `street_type` = 'pavilon';
REPLACE INTO `street_types` SET `street_type` = 'pálya';
REPLACE INTO `street_types` SET `street_type` = 'pályaudvar';
REPLACE INTO `street_types` SET `street_type` = 'piac';
REPLACE INTO `street_types` SET `street_type` = 'pihenő';
REPLACE INTO `street_types` SET `street_type` = 'pince';
REPLACE INTO `street_types` SET `street_type` = 'pincesor';
REPLACE INTO `street_types` SET `street_type` = 'postafiók';
REPLACE INTO `street_types` SET `street_type` = 'puszta';
REPLACE INTO `street_types` SET `street_type` = 'rakpart';
REPLACE INTO `street_types` SET `street_type` = 'repülőtér';
REPLACE INTO `street_types` SET `street_type` = 'rész';
REPLACE INTO `street_types` SET `street_type` = 'rét';
REPLACE INTO `street_types` SET `street_type` = 'sarok';
REPLACE INTO `street_types` SET `street_type` = 'sánc';
REPLACE INTO `street_types` SET `street_type` = 'sávház';
REPLACE INTO `street_types` SET `street_type` = 'sétány';
REPLACE INTO `street_types` SET `street_type` = 'sor';
REPLACE INTO `street_types` SET `street_type` = 'sora';
REPLACE INTO `street_types` SET `street_type` = 'sportpálya';
REPLACE INTO `street_types` SET `street_type` = 'sporttelep';
REPLACE INTO `street_types` SET `street_type` = 'stadion';
REPLACE INTO `street_types` SET `street_type` = 'strandfürdő';
REPLACE INTO `street_types` SET `street_type` = 'sugárút';
REPLACE INTO `street_types` SET `street_type` = 'szállás';
REPLACE INTO `street_types` SET `street_type` = 'szállások';
REPLACE INTO `street_types` SET `street_type` = 'szer';
REPLACE INTO `street_types` SET `street_type` = 'szél';
REPLACE INTO `street_types` SET `street_type` = 'sziget';
REPLACE INTO `street_types` SET `street_type` = 'szivattyútelep';
REPLACE INTO `street_types` SET `street_type` = 'szőlő';
REPLACE INTO `street_types` SET `street_type` = 'szőlőhegy';
REPLACE INTO `street_types` SET `street_type` = 'szőlők';
REPLACE INTO `street_types` SET `street_type` = 'tag';
REPLACE INTO `street_types` SET `street_type` = 'tanya';
REPLACE INTO `street_types` SET `street_type` = 'tanyák';
REPLACE INTO `street_types` SET `street_type` = 'telep';
REPLACE INTO `street_types` SET `street_type` = 'temető';
REPLACE INTO `street_types` SET `street_type` = 'tere';
REPLACE INTO `street_types` SET `street_type` = 'tető';
REPLACE INTO `street_types` SET `street_type` = 'téli kikötő';
REPLACE INTO `street_types` SET `street_type` = 'tömb';
REPLACE INTO `street_types` SET `street_type` = 'turistaház';
REPLACE INTO `street_types` SET `street_type` = 'udvar';
REPLACE INTO `street_types` SET `street_type` = 'utak';
REPLACE INTO `street_types` SET `street_type` = 'utcája';
REPLACE INTO `street_types` SET `street_type` = 'útja';
REPLACE INTO `street_types` SET `street_type` = 'útőrház';
REPLACE INTO `street_types` SET `street_type` = 'üdülő';
REPLACE INTO `street_types` SET `street_type` = 'üdülő-part';
REPLACE INTO `street_types` SET `street_type` = 'üdülő-sor';
REPLACE INTO `street_types` SET `street_type` = 'üdülő-telep';
REPLACE INTO `street_types` SET `street_type` = 'vadaskert';
REPLACE INTO `street_types` SET `street_type` = 'vadászház';
REPLACE INTO `street_types` SET `street_type` = 'vasútállomás';
REPLACE INTO `street_types` SET `street_type` = 'vasúti megálló';
REPLACE INTO `street_types` SET `street_type` = 'vasúti őrház';
REPLACE INTO `street_types` SET `street_type` = 'vasútsor';
REPLACE INTO `street_types` SET `street_type` = 'vágóhíd';
REPLACE INTO `street_types` SET `street_type` = 'vár';
REPLACE INTO `street_types` SET `street_type` = 'várköz';
REPLACE INTO `street_types` SET `street_type` = 'város';
REPLACE INTO `street_types` SET `street_type` = 'vezetőút';
REPLACE INTO `street_types` SET `street_type` = 'villasor';
REPLACE INTO `street_types` SET `street_type` = 'vízmű';
REPLACE INTO `street_types` SET `street_type` = 'völgy';
REPLACE INTO `street_types` SET `street_type` = 'zsilip';
REPLACE INTO `street_types` SET `street_type` = 'zug';


DELETE FROM nationality_marks;


Insert into nationality_marks ( mark, name) VALUES ('H','Magyarország');

Insert into nationality_marks ( mark, name) VALUES ('A','Ausztria');
Insert into nationality_marks ( mark, name) VALUES ('B','Belgium');
Insert into nationality_marks ( mark, name) VALUES ('BG','Bulgária');
Insert into nationality_marks ( mark, name) VALUES ('BIH','Bosznia-Hercegovina');
Insert into nationality_marks ( mark, name) VALUES ('CH','Svájc');
Insert into nationality_marks ( mark, name) VALUES ('CZ','Csehország');
Insert into nationality_marks ( mark, name) VALUES ('D','Németország');
Insert into nationality_marks ( mark, name) VALUES ('DK','Dánia');
Insert into nationality_marks ( mark, name) VALUES ('E','Spanyolország');
Insert into nationality_marks ( mark, name) VALUES ('F','Franciaország (és területei)');
Insert into nationality_marks ( mark, name) VALUES ('FIN','Finnország');
Insert into nationality_marks ( mark, name) VALUES ('GB','Egyesült Királyság');
Insert into nationality_marks ( mark, name) VALUES ('GR','Görögország');
Insert into nationality_marks ( mark, name) VALUES ('HR','Horvátország');
Insert into nationality_marks ( mark, name) VALUES ('I','Olaszország');
Insert into nationality_marks ( mark, name) VALUES ('IL','Izrael');
Insert into nationality_marks ( mark, name) VALUES ('L','Luxemburg');
Insert into nationality_marks ( mark, name) VALUES ('N','Norvégia');
Insert into nationality_marks ( mark, name) VALUES ('NL','Hollandia');
Insert into nationality_marks ( mark, name) VALUES ('P','Portugália');
Insert into nationality_marks ( mark, name) VALUES ('PL','Lengyelország');
Insert into nationality_marks ( mark, name) VALUES ('RO','Románia');
Insert into nationality_marks ( mark, name) VALUES ('S','Svédország');
Insert into nationality_marks ( mark, name) VALUES ('SCO','Skócia');
Insert into nationality_marks ( mark, name) VALUES ('SK','Szlovákia');
Insert into nationality_marks ( mark, name) VALUES ('SLO','Szlovénia');
Insert into nationality_marks ( mark, name) VALUES ('SRB','Szerbia');
Insert into nationality_marks ( mark, name) VALUES ('UA','Ukrajna');



Insert into nationality_marks ( mark, name) VALUES ('AFG','Afganisztán');
Insert into nationality_marks ( mark, name) VALUES ('AG','Antigua és Barbuda');
Insert into nationality_marks ( mark, name) VALUES ('AL','Albánia');
Insert into nationality_marks ( mark, name) VALUES ('AM','Örményország');
Insert into nationality_marks ( mark, name) VALUES ('ANG','Angola');
Insert into nationality_marks ( mark, name) VALUES ('AND','Andorra');
Insert into nationality_marks ( mark, name) VALUES ('AUS','Ausztrália (és külbirtokai)');
Insert into nationality_marks ( mark, name) VALUES ('AZ','Azerbajdzsán');
Insert into nationality_marks ( mark, name) VALUES ('BD','Banglades');
Insert into nationality_marks ( mark, name) VALUES ('BDS','Barbados');
Insert into nationality_marks ( mark, name) VALUES ('BER','Bermuda');
Insert into nationality_marks ( mark, name) VALUES ('BF','Burkina Faso');
Insert into nationality_marks ( mark, name) VALUES ('BHT','Bhután');
Insert into nationality_marks ( mark, name) VALUES ('BOL','Bolívia');
Insert into nationality_marks ( mark, name) VALUES ('BR','Brazília');
Insert into nationality_marks ( mark, name) VALUES ('BRN','Bahrein');
Insert into nationality_marks ( mark, name) VALUES ('BRU','Brunei');
Insert into nationality_marks ( mark, name) VALUES ('BS','Bahama-szigetek');
Insert into nationality_marks ( mark, name) VALUES ('BU','Burundi');
Insert into nationality_marks ( mark, name) VALUES ('BW','Botswana');
Insert into nationality_marks ( mark, name) VALUES ('BY','Fehéroroszország (Belarusz)');
Insert into nationality_marks ( mark, name) VALUES ('BZ','Belize');
Insert into nationality_marks ( mark, name) VALUES ('C','Kuba');
Insert into nationality_marks ( mark, name) VALUES ('CAM','Kamerun');
Insert into nationality_marks ( mark, name) VALUES ('CC', 'Konzulátusi testület');
Insert into nationality_marks ( mark, name) VALUES ('CD', 'Diplomáciai testület');
Insert into nationality_marks ( mark, name) VALUES ('CI','Elefántcsontpart');
Insert into nationality_marks ( mark, name) VALUES ('CL','Srí Lanka');
Insert into nationality_marks ( mark, name) VALUES ('CO','Kolumbia');
Insert into nationality_marks ( mark, name) VALUES ('COM','Comore-szigetek');
Insert into nationality_marks ( mark, name) VALUES ('CR','Costa Rica');
Insert into nationality_marks ( mark, name) VALUES ('CV','Zöld-foki Köztársaság');
Insert into nationality_marks ( mark, name) VALUES ('CY','Ciprus');



Insert into nationality_marks ( mark, name) VALUES ('DJ','Dzsibuti');
Insert into nationality_marks ( mark, name) VALUES ('DOM','Dominikai Köztársaság');
Insert into nationality_marks ( mark, name) VALUES ('DPR', 'Észak-Korea');
Insert into nationality_marks ( mark, name) VALUES ('DRC','Kongói Demokratikus Köztársaság (Zaire)');
Insert into nationality_marks ( mark, name) VALUES ('DY','Benin');
Insert into nationality_marks ( mark, name) VALUES ('DZ','Algéria');
Insert into nationality_marks ( mark, name) VALUES ('EAK','Kenya');
Insert into nationality_marks ( mark, name) VALUES ('EAT','Tanzánia');
Insert into nationality_marks ( mark, name) VALUES ('EAU','Uganda');
Insert into nationality_marks ( mark, name) VALUES ('EC','Ecuador');
Insert into nationality_marks ( mark, name) VALUES ('ER','Eritrea');
Insert into nationality_marks ( mark, name) VALUES ('ES','El Salvador');
Insert into nationality_marks ( mark, name) VALUES ('EST','Észtország');
Insert into nationality_marks ( mark, name) VALUES ('ET','Egyiptom    ');
Insert into nationality_marks ( mark, name) VALUES ('ETH','Etiópia');
Insert into nationality_marks ( mark, name) VALUES ('EUR','Európai Unió hivatali gépjárművek');
Insert into nationality_marks ( mark, name) VALUES ('FJI','Fidzsi-szigetek');
Insert into nationality_marks ( mark, name) VALUES ('FL','Liechtenstein');
Insert into nationality_marks ( mark, name) VALUES ('FO','Feröer');
Insert into nationality_marks ( mark, name) VALUES ('FSM','Mikronézia');
Insert into nationality_marks ( mark, name) VALUES ('G','Gabon');
Insert into nationality_marks ( mark, name) VALUES ('GBA', 'Alderney Alderney (Guernsey)');
Insert into nationality_marks ( mark, name) VALUES ('GBG','Guernsey');
Insert into nationality_marks ( mark, name) VALUES ('GBJ','Jersey');
Insert into nationality_marks ( mark, name) VALUES ('GBM','Man');
Insert into nationality_marks ( mark, name) VALUES ('GBZ','Gibraltár');
Insert into nationality_marks ( mark, name) VALUES ('GCA','Guatemala');
Insert into nationality_marks ( mark, name) VALUES ('GE','Grúzia');
Insert into nationality_marks ( mark, name) VALUES ('GH','Ghána');
Insert into nationality_marks ( mark, name) VALUES ('GUY','Guyana');
Insert into nationality_marks ( mark, name) VALUES ('HK','Hongkong');
Insert into nationality_marks ( mark, name) VALUES ('HKJ','Jordánia');
Insert into nationality_marks ( mark, name) VALUES ('HN','Honduras');
Insert into nationality_marks ( mark, name) VALUES ('IND','India');
Insert into nationality_marks ( mark, name) VALUES ('IR','Irán');
Insert into nationality_marks ( mark, name) VALUES ('IRL','Írország');
Insert into nationality_marks ( mark, name) VALUES ('IRQ','Irak');
Insert into nationality_marks ( mark, name) VALUES ('IS','Izland');
Insert into nationality_marks ( mark, name) VALUES ('J','Japán');
Insert into nationality_marks ( mark, name) VALUES ('JA','Jamaica');
Insert into nationality_marks ( mark, name) VALUES ('K','Kambodzsa');
Insert into nationality_marks ( mark, name) VALUES ('KIR','Kiribati');
Insert into nationality_marks ( mark, name) VALUES ('KN','Saint Kitts és Nevis');
Insert into nationality_marks ( mark, name) VALUES ('KS','Kirgizisztán');
Insert into nationality_marks ( mark, name) VALUES ('KWT','Kuvait');
Insert into nationality_marks ( mark, name) VALUES ('KZ','Kazahsztán');
Insert into nationality_marks ( mark, name) VALUES ('LAO','Laosz');
Insert into nationality_marks ( mark, name) VALUES ('LAR','Líbia');
Insert into nationality_marks ( mark, name) VALUES ('LB','Libéria');
Insert into nationality_marks ( mark, name) VALUES ('LS','Lesotho');
Insert into nationality_marks ( mark, name) VALUES ('LT','Litvánia');
Insert into nationality_marks ( mark, name) VALUES ('LV','Lettország');
Insert into nationality_marks ( mark, name) VALUES ('M','Málta');
Insert into nationality_marks ( mark, name) VALUES ('MA','Marokkó');
Insert into nationality_marks ( mark, name) VALUES ('MAL','Malajzia');
Insert into nationality_marks ( mark, name) VALUES ('MC','Monaco');
Insert into nationality_marks ( mark, name) VALUES ('MD','Moldova');
Insert into nationality_marks ( mark, name) VALUES ('MEX','Mexikó');
Insert into nationality_marks ( mark, name) VALUES ('MGL','Mongólia');
Insert into nationality_marks ( mark, name) VALUES ('MH','Marshall-szigetek');
Insert into nationality_marks ( mark, name) VALUES ('MK','Macedónia');
Insert into nationality_marks ( mark, name) VALUES ('MNE','Montenegró');
Insert into nationality_marks ( mark, name) VALUES ('MOC','Mozambik');
Insert into nationality_marks ( mark, name) VALUES ('MS','Mauritius');
Insert into nationality_marks ( mark, name) VALUES ('MV','Maldív-szigetek');
Insert into nationality_marks ( mark, name) VALUES ('MW','Malawi');
Insert into nationality_marks ( mark, name) VALUES ('MYA','Mianmar (Burma)');
Insert into nationality_marks ( mark, name) VALUES ('NA','Holland Antillák');
Insert into nationality_marks ( mark, name) VALUES ('NAM','Namíbia');
Insert into nationality_marks ( mark, name) VALUES ('NAU','Nauru');
Insert into nationality_marks ( mark, name) VALUES ('NEP','Nepál');
Insert into nationality_marks ( mark, name) VALUES ('NGR','Nigéria');
Insert into nationality_marks ( mark, name) VALUES ('NIC','Nicaragua');
Insert into nationality_marks ( mark, name) VALUES ('NZ','Új-Zéland (és területei)');
Insert into nationality_marks ( mark, name) VALUES ('OM','Omán');
Insert into nationality_marks ( mark, name) VALUES ('PA','Panama');
Insert into nationality_marks ( mark, name) VALUES ('PAL','Palau');
Insert into nationality_marks ( mark, name) VALUES ('PK','Pakisztán');
Insert into nationality_marks ( mark, name) VALUES ('PE','Peru');
Insert into nationality_marks ( mark, name) VALUES ('PNG','Pápua Új-Guinea');
Insert into nationality_marks ( mark, name) VALUES ('PRC','Kína');
Insert into nationality_marks ( mark, name) VALUES ('PY','Paraguay');
Insert into nationality_marks ( mark, name) VALUES ('Q','Katar');
Insert into nationality_marks ( mark, name) VALUES ('RA','Argentína');
Insert into nationality_marks ( mark, name) VALUES ('RB','Botswana (nem hivatalosan a BW-t is használják)');
Insert into nationality_marks ( mark, name) VALUES ('RC','Tajvan');
Insert into nationality_marks ( mark, name) VALUES ('RCA','Közép-Afrika');
Insert into nationality_marks ( mark, name) VALUES ('RCB','Kongói Köztársaság');
Insert into nationality_marks ( mark, name) VALUES ('RCH','Chile');
Insert into nationality_marks ( mark, name) VALUES ('RG','Guinea');
Insert into nationality_marks ( mark, name) VALUES ('RGB','Bissau-Guinea');
Insert into nationality_marks ( mark, name) VALUES ('RGE','Egyenlítői-Guinea');
Insert into nationality_marks ( mark, name) VALUES ('RH','Haiti');
Insert into nationality_marks ( mark, name) VALUES ('RI','Indonézia');
Insert into nationality_marks ( mark, name) VALUES ('RIM','Mauritánia');
Insert into nationality_marks ( mark, name) VALUES ('RL','Libanon');
Insert into nationality_marks ( mark, name) VALUES ('RM','Madagaszkár');
Insert into nationality_marks ( mark, name) VALUES ('RMM','Mali');
Insert into nationality_marks ( mark, name) VALUES ('RN','Niger');
Insert into nationality_marks ( mark, name) VALUES ('ROK','Dél-Korea');
Insert into nationality_marks ( mark, name) VALUES ('ROU','Uruguay');
Insert into nationality_marks ( mark, name) VALUES ('RP','Fülöp-szigetek');
Insert into nationality_marks ( mark, name) VALUES ('RSL','Szomáliföld');
Insert into nationality_marks ( mark, name) VALUES ('RSM','San Marino');
Insert into nationality_marks ( mark, name) VALUES ('RUS','Oroszország');
Insert into nationality_marks ( mark, name) VALUES ('RWA','Ruanda');
Insert into nationality_marks ( mark, name) VALUES ('SA','Szaúd-Arábia');
Insert into nationality_marks ( mark, name) VALUES ('SD','Szváziföld');
Insert into nationality_marks ( mark, name) VALUES ('SGP','Szingapúr');
Insert into nationality_marks ( mark, name) VALUES ('SME','Suriname');
Insert into nationality_marks ( mark, name) VALUES ('SN','Szenegál');
Insert into nationality_marks ( mark, name) VALUES ('SO','Szomália');
Insert into nationality_marks ( mark, name) VALUES ('SOL','Salamon-szigetek');
Insert into nationality_marks ( mark, name) VALUES ('STP','Sao Tomé és Príncipe');
Insert into nationality_marks ( mark, name) VALUES ('SUD','Szudán');
Insert into nationality_marks ( mark, name) VALUES ('SY','Seychelle-szigetek');
Insert into nationality_marks ( mark, name) VALUES ('SYR','Szíria');
Insert into nationality_marks ( mark, name) VALUES ('T','Thaiföld');
Insert into nationality_marks ( mark, name) VALUES ('TCH','Csád');
Insert into nationality_marks ( mark, name) VALUES ('TG','Togo');
Insert into nationality_marks ( mark, name) VALUES ('TGA','Tonga');
Insert into nationality_marks ( mark, name) VALUES ('TJ','Tádzsikisztán');
Insert into nationality_marks ( mark, name) VALUES ('TK','Tokelau-szigetek');
Insert into nationality_marks ( mark, name) VALUES ('TM','Türkmenisztán');
Insert into nationality_marks ( mark, name) VALUES ('TMP','Kelet-Timor');
Insert into nationality_marks ( mark, name) VALUES ('TN','Tunézia');
Insert into nationality_marks ( mark, name) VALUES ('TR','Törökország');
Insert into nationality_marks ( mark, name) VALUES ('TT','Trinidad és Tobago');
Insert into nationality_marks ( mark, name) VALUES ('TV','Tuvalu');
Insert into nationality_marks ( mark, name) VALUES ('UAE','Egyesült Arab Emírségek');
Insert into nationality_marks ( mark, name) VALUES ('USA','USA');
Insert into nationality_marks ( mark, name) VALUES ('UZ','Üzbegisztán');
Insert into nationality_marks ( mark, name) VALUES ('V','Vatikán');
Insert into nationality_marks ( mark, name) VALUES ('VAN', 'Vanuatu');
Insert into nationality_marks ( mark, name) VALUES ('VN','Vietnam');
Insert into nationality_marks ( mark, name) VALUES ('WAG','Gambia');
Insert into nationality_marks ( mark, name) VALUES ('WAL','Sierra Leone');
Insert into nationality_marks ( mark, name) VALUES ('WD','Dominikai Közösség');
Insert into nationality_marks ( mark, name) VALUES ('WG','Grenada');
Insert into nationality_marks ( mark, name) VALUES ('WL','Saint Lucia');
Insert into nationality_marks ( mark, name) VALUES ('WS','Szamoa');
Insert into nationality_marks ( mark, name) VALUES ('WV','Saint Vincent és a Grenadine-szigetek');
Insert into nationality_marks ( mark, name) VALUES ('Y,YAR','Jemen (az Y nem hivatalosan használt jelzés)');
Insert into nationality_marks ( mark, name) VALUES ('YV','Venezuela');
Insert into nationality_marks ( mark, name) VALUES ('Z','Zambia');
Insert into nationality_marks ( mark, name) VALUES ('ZA','Dél-afrikai Köztársaság');
Insert into nationality_marks ( mark, name) VALUES ('ZW','Zimbabwe');


